export const SITE = {
  title: 'Stickman Hook',
  description: 'Play Stickman Hook online free. Swing through 100+ levels with your grappling hook — no download, instant play in your browser.',
  url: 'https://stickman-hook.co.uk',
  locale: 'en_GB',
  gameEmbedUrl: 'https://stickmanhookgame.org/stickman-hook.embed',
  gameHost: 'stickmanhookgame.org',
  twitterHandle: '@StickmanHookGame',
  ogImage: '/og/home.png',   // generated by src/pages/og/[page].png.ts
  developer: 'Madbox',
  releaseDate: '2018-10-03',
  rating: '4+',
  genre: 'Arcade',
  gamePlatform: ['Web browser', 'iOS', 'Android'],
  appStoreUrl: 'https://apps.apple.com/app/stickman-hook/id1430021754',
  googlePlayUrl: 'https://play.google.com/store/apps/details?id=com.madbox.stickmanswing',
};

export const NAV_LINKS = [
  { label: 'Play', href: '/' },
  { label: 'Unblocked', href: '/unblocked/' },
  { label: 'How to Play', href: '/how-to-play/' },
  { label: 'Levels', href: '/levels/' },
  { label: 'Skins', href: '/skins/' },
  { label: 'FAQ', href: '/faq/' },
  { label: 'More Games', href: '/games/' },
];
